# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistemaescolar?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# Coloca aquí tu contraseña de MySQL, déjalo en blanco si no usas contraseña
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ejecutar scripts SQL iniciales (opcional, si deseas que se sigan corriendo tus archivos data.sql)
spring.sql.init.mode=always
spring.sql.init.defer-datasource-initialization=true